a = int(input())
b = int(input())
num = a*int(str(b)[2])
num1 = a*int(str(b)[1])
num2 = a*int(str(b)[0])

print(num)
print(num1)
print(num2)
print(num1*10+num2*100+num)

# 좀 효율적으로(원래 이렇게 하면 좋았을 텐데...)
a = int(input())
b = input()
num = a*int(b[2])
num1 = a*int(b[1])
num2 = a*int(b[0])

print(num)
print(num1)
print(num2)
print(num1*10+num2*100+num)